#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn pre-commit
yarn pre-commit
yarn pre-commit
yarn pre-commit
yarn pre-commit
yarn pre-commit
yarn pre-commit
yarn pre-commit
yarn pre-commit
yarn pre-commit
yarn pre-commit
